"""LoomCraft — an AI-native DAG planning and execution engine.

An agent proposes a versioned task DAG through a validated tool surface; the
server checks it, executes the parts it is authorised to execute, streams every
state change as an event, and the renderer draws it.

Typical wiring::

    from loomcraft import Registry, Capability, Session, ToolBroker, AnthropicAgent

    registry = Registry()

    @registry.capability_runner(Capability(
        id="csv.profile",
        name="Profile a CSV",
        description="Column types, null counts, and basic statistics.",
        runner="csv.profile",
        inputs=(CapabilityInput(key="table", name="Table", description="CSV",
                                allowed_extensions=(".csv",)),),
        outputs=(Port(name="profile", artifact_type="json"),),
    ))
    async def profile(ctx: NodeContext) -> NodeResult:
        ...

    session = SessionStore("./data").create()
    broker = ToolBroker(session, registry)
    await AnthropicAgent().run_turn(broker, "Profile the uploaded table.")

See ``docs/`` for the full guide.
"""

from __future__ import annotations

__version__ = "0.1.0"

from .agent import (
    Agent,
    AnthropicAgent,
    OpenAICompatibleAgent,
    ScriptedAgent,
    ToolCall,
    TurnResult,
    execute_tool_calls,
)
from .broker import BrokerLimits, ToolBroker, ToolResponse
from .dag import DAGValidationError, NODE_TYPES, plan_from_dag, validate_dag
from .ai import (
    AIProvider,
    AIProviderError,
    AIResponse,
    AIStreamEvent,
    AgentRunResult,
    CodexCLIProvider,
    JsonlSubprocessProvider,
    OpenAICompatibleProvider,
    PlannerAgent,
    ResponsesAPIProvider,
    ScriptedProvider,
    StreamingAIProvider,
    parse_chat_response,
    parse_responses_response,
    openai_tool_specs,
    provider_from_env,
)
from .context import (
    EmittedArtifact,
    InputFile,
    NodeContext,
    NodeResult,
    Runner,
    RunnerFn,
)
from .engine import (
    Engine,
    ExecutionGraph,
    ExecutionNode,
    NodeState,
    Run,
    graph_from_capability,
    graph_from_workflow,
    MAX_RESULT_DETAIL_BYTES,
)
from .errors import (
    ArtifactError,
    BrokerError,
    ContractError,
    DependencyError,
    EventLogError,
    ExecutionError,
    RunCancelledError,
    RunTimeoutError,
    GraphStalledError,
    InactiveRunWriteError,
    InputRequestError,
    InputRequestValidationError,
    LoomCraftError,
    PlanValidationError,
    RegistryError,
    SourceError,
    SourceIntegrityError,
    StepTransitionError,
    UnknownCapabilityError,
    UnknownStepError,
    UnknownWorkflowError,
    UnsupportedActionError,
    InvalidArgumentError,
    ActionBudgetError,
    RepeatedActionError,
    AwaitingInputsError,
    ExecutionBusyError,
    KnowledgeUnavailableError,
)
from .events import EVENT_TYPES, Event, EventLog, MemoryEventLog, encode_sse, iter_sse
from .graph import (
    critical_path,
    find_cycle,
    is_dag,
    layers,
    topological_order,
    to_dot,
)
from .inputs import (
    FileInputRequest,
    FileRequirement,
    allocate_input_uploads,
    allocate_uploads,
    validate_input_fulfillment,
    validate_fulfillment,
    validate_input_request,
)
from .plan import (
    AGENT_REPORTABLE_KINDS,
    AnalysisCoverage,
    AnalysisCoverageStatus,
    AnalysisObjective,
    DEFAULT_MAX_STEPS,
    FAILURE_POLICIES,
    MAX_PLAN_STEPS,
    MAX_INPUT_REQUIREMENTS,
    MAX_REVISION,
    MAX_STEPS,
    RetryPolicy,
    RUN_STATUSES,
    STEP_KINDS,
    STEP_TRANSITIONS,
    Plan,
    PlanStep,
    StepKind,
    StepStatus,
    get_step,
    parse_plan,
    propagate_skips,
    diff_plans,
    task_phase,
    topological_layers,
    topological_order as plan_topological_order,
    update_step,
    validate_plan,
)
from .plan_executor import PlanExecutor, PlanNodeContext, build_plan_graph
from .legacy_executor import (
    ApprovalRequired,
    DAGExecutor,
    ExecutionResult,
    StepContext,
    StepOutcome,
)
from .registry import (
    Capability,
    CapabilityInput,
    CapabilitySpec,
    Parameter,
    Port,
    Registry,
    StepResult,
    Workflow,
    WorkflowSpec,
    WorkflowNode,
    invoke_handler,
    merge_registries,
    source_ref_of,
)
from .store import (
    ResolvedSource,
    Session,
    SessionStore,
    public_artifact,
    public_execution,
    public_plan,
)
from .legacy_storage import (
    InMemoryStore,
    JsonStore,
    SessionStore as LegacySessionStore,
    SessionStoreProtocol,
)
from .tools import (
    EXECUTE_PLAN,
    EXTENDED_TOOLS,
    INSPECT_TABLE,
    KNOWLEDGE_LIST,
    KNOWLEDGE_READ,
    KNOWLEDGE_SEARCH,
    OPERATION_SEARCH,
    REGISTER_ARTIFACT,
    SYSTEM_PROMPT,
    ToolSpec,
    anthropic_tools,
    mcp_tools,
    openai_tools,
    to_dialect,
    tool_specs,
    extended_tool_specs,
    dynamic_tool_specs,
)
from .inspection import InspectionError, inspect_table_file
from .knowledge import InMemoryKnowledgeProvider, KnowledgePathError, normalize_path
from .protocol import AppServerBridge, ProtocolError
from .server import TurnManager, create_app, create_router, json_line, sse_payload
from .runtime import LoomcraftRuntime, create_fastapi_router
from .uploads import LocalUploadStore, UploadError
from .artifacts import ArtifactStoreError, LocalArtifactStore
from .sources_compat import SourceResolutionError, SourceResolver

__all__ = [
    "__version__",
    # Plan
    "AGENT_REPORTABLE_KINDS",
    "Plan",
    "PlanStep",
    "STEP_TRANSITIONS",
    "StepKind",
    "StepStatus",
    "get_step",
    "parse_plan",
    "propagate_skips",
    "update_step",
    "validate_plan",
    "diff_plans",
    "task_phase",
    "topological_layers",
    "plan_topological_order",
    "DAGValidationError",
    "NODE_TYPES",
    "plan_from_dag",
    "validate_dag",
    "AnalysisCoverage",
    "AnalysisCoverageStatus",
    "AnalysisObjective",
    "DEFAULT_MAX_STEPS",
    "FAILURE_POLICIES",
    "MAX_PLAN_STEPS",
    "MAX_INPUT_REQUIREMENTS",
    "MAX_REVISION",
    "MAX_STEPS",
    "RUN_STATUSES",
    "RetryPolicy",
    "STEP_KINDS",
    # Graph
    "critical_path",
    "find_cycle",
    "is_dag",
    "layers",
    "to_dot",
    "topological_order",
    # Registry
    "Capability",
    "CapabilityInput",
    "CapabilitySpec",
    "Parameter",
    "Port",
    "Registry",
    "StepResult",
    "Workflow",
    "WorkflowSpec",
    "WorkflowNode",
    "invoke_handler",
    "merge_registries",
    "source_ref_of",
    # Execution
    "Engine",
    "ExecutionGraph",
    "ExecutionNode",
    "NodeContext",
    "NodeResult",
    "NodeState",
    "Run",
    "Runner",
    "RunnerFn",
    "EmittedArtifact",
    "InputFile",
    "graph_from_capability",
    "graph_from_workflow",
    "MAX_RESULT_DETAIL_BYTES",
    "PlanExecutor",
    "PlanNodeContext",
    "build_plan_graph",
    "DAGExecutor",
    "ApprovalRequired",
    "ExecutionResult",
    "StepContext",
    "StepOutcome",
    # Session / events
    "EVENT_TYPES",
    "Event",
    "EventLog",
    "MemoryEventLog",
    "encode_sse",
    "iter_sse",
    "ResolvedSource",
    "Session",
    "SessionStore",
    "public_artifact",
    "public_execution",
    "public_plan",
    "LegacySessionStore",
    "SessionStoreProtocol",
    "InMemoryStore",
    "JsonStore",
    # Inputs
    "FileInputRequest",
    "FileRequirement",
    "allocate_uploads",
    "allocate_input_uploads",
    "validate_fulfillment",
    "validate_input_fulfillment",
    "validate_input_request",
    # Agent surface
    "Agent",
    "AnthropicAgent",
    "BrokerLimits",
    "OpenAICompatibleAgent",
    "SYSTEM_PROMPT",
    "ScriptedAgent",
    "ToolBroker",
    "ToolCall",
    "ToolResponse",
    "ToolSpec",
    "TurnResult",
    "anthropic_tools",
    "execute_tool_calls",
    "mcp_tools",
    "openai_tools",
    "to_dialect",
    "tool_specs",
    "extended_tool_specs",
    "dynamic_tool_specs",
    "EXECUTE_PLAN",
    "EXTENDED_TOOLS",
    "INSPECT_TABLE",
    "KNOWLEDGE_LIST",
    "KNOWLEDGE_READ",
    "KNOWLEDGE_SEARCH",
    "OPERATION_SEARCH",
    "REGISTER_ARTIFACT",
    # Errors
    "ArtifactError",
    "BrokerError",
    "ContractError",
    "DependencyError",
    "EventLogError",
    "ExecutionError",
    "RunCancelledError",
    "RunTimeoutError",
    "GraphStalledError",
    "InactiveRunWriteError",
    "InputRequestError",
    "InputRequestValidationError",
    "LoomCraftError",
    "PlanValidationError",
    "RegistryError",
    "SourceError",
    "SourceIntegrityError",
    "StepTransitionError",
    "UnknownCapabilityError",
    "UnknownStepError",
    "UnknownWorkflowError",
    "UnsupportedActionError",
    "InvalidArgumentError",
    "ActionBudgetError",
    "RepeatedActionError",
    "AwaitingInputsError",
    "ExecutionBusyError",
    "KnowledgeUnavailableError",
    "AIProvider",
    "AIProviderError",
    "AIResponse",
    "AIStreamEvent",
    "AgentRunResult",
    "CodexCLIProvider",
    "JsonlSubprocessProvider",
    "OpenAICompatibleProvider",
    "PlannerAgent",
    "ResponsesAPIProvider",
    "ScriptedProvider",
    "StreamingAIProvider",
    "parse_chat_response",
    "parse_responses_response",
    "openai_tool_specs",
    "provider_from_env",
    "InspectionError",
    "inspect_table_file",
    "InMemoryKnowledgeProvider",
    "KnowledgePathError",
    "normalize_path",
    "AppServerBridge",
    "ProtocolError",
    "LocalUploadStore",
    "UploadError",
    "ArtifactStoreError",
    "LocalArtifactStore",
    "SourceResolutionError",
    "SourceResolver",
    "TurnManager",
    "create_app",
    "create_router",
    "create_fastapi_router",
    "json_line",
    "sse_payload",
    "LoomcraftRuntime",
]
